# Generated by Django 5.0.6 on 2024-07-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abilities', models.TextField()),
                ('config', models.JSONField(blank=True, default=dict)),
                ('input_format', models.TextField()),
                ('output_format', models.TextField()),
            ],
        ),
    ]
