# Generated by Django 5.0.6 on 2024-07-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_toolinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='tool_class_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
