# Generated by Django 5.0.6 on 2024-07-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_tool_tool_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolinstance',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
