# Generated by Django 5.0.6 on 2024-07-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_toolinstance_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='persist_in_memory',
            field=models.BooleanField(default=False),
        ),
    ]
