# Generated by Django 5.0.6 on 2024-07-05 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_tool_persist_in_memory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='persist_in_memory',
        ),
    ]
