# Generated by Django 5.0.6 on 2024-07-03 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llm_model', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('goal', models.TextField()),
                ('backstory', models.TextField()),
                ('max_iter', models.IntegerField(default=25)),
                ('max_rpm', models.IntegerField(blank=True, null=True)),
                ('max_execution_time', models.IntegerField(blank=True, null=True)),
                ('system_template', models.TextField(blank=True, null=True)),
                ('prompt_template', models.TextField(blank=True, null=True)),
                ('response_template', models.TextField(blank=True, null=True)),
                ('internal_agents', models.ManyToManyField(blank=True, related_name='parent_agents', to='agents.agent')),
                ('llm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='agents.llm')),
                ('tools', models.ManyToManyField(blank=True, related_name='agents', to='agents.tool')),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='agents.agent')),
                ('to_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='agents.agent')),
            ],
        ),
    ]
