# Generated by Django 5.0.6 on 2024-07-04 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0002_remove_node_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_handle', models.CharField(default=None, max_length=128)),
                ('target_handle', models.CharField(default=None, max_length=128)),
                ('identifier', models.CharField(default=None, max_length=128)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_edges', to='layout.node')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_edges', to='layout.node')),
            ],
        ),
    ]
