# Generated by Django 5.0.6 on 2024-07-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0003_edge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='source_handle',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='target_handle',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
