# Generated by Django 5.0.6 on 2024-07-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0004_alter_edge_source_handle_alter_edge_target_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='layout_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
