# Generated by Django 5.0.6 on 2024-07-04 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0005_node_layout_data'),
        ('tools', '0002_toolinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='tool_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.toolinstance'),
        ),
    ]
