# Generated by Django 5.0.6 on 2024-07-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0006_node_tool_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='goal_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='node',
            name='instructions_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='node',
            name='personality_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='node',
            name='role_prompt',
            field=models.TextField(blank=True),
        ),
    ]
