# Generated by Django 5.0.6 on 2024-07-06 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0007_node_goal_prompt_node_instructions_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='entry_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='layout.node'),
        ),
    ]
