# Generated by Django 5.0.6 on 2024-07-07 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization_created_by'),
        ('layout', '0008_node_entry_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='core.project'),
        ),
    ]
